url: 'http://0.0.0.0:4000'
timezone: America/Los_Angeles
exclude: ['Gemfile', 'Gemfile.lock', 'README.md', 'Gruntfile.js', 'package.json', 'sass', 'node_modules', '/js', '/images']
company: 'Palantir'
title: 'Palantir'
google_analytics: ''
